### ISSUE TITLE
test 2 line fillets fail.

### ISSUE THREAD

**Issue by krcwrhvgyxzqelljes** [a-downing/clothoid#2]
auto shape1 = Line(0, 10, -10, 0);
 auto shape2 = Line(1, 10, 10, 0);

![Figure_1](https://github.com/a-downing/clothoid/assets/167009475/f2e0fca2-d6f9-412d-bb67-4d72f2e4415b)

**Comment by a-downing** [comment]
I should add some notes somewhere to explain more how this works. The shapes have to be defined in a way so that the starting point of the second shape is the ending point of the first shape (in this example they don't join, but they're close enough to still work). 

Unfortunately even when I change the order of the points this happens instead, so something else is still wrong.
![image](https://github.com/a-downing/clothoid/assets/1827346/9658d66a-20e1-4919-a8e9-285d275c4f53)
![image](https://github.com/a-downing/clothoid/assets/1827346/a5bc07e2-2938-4103-b46b-5919e1d785e5)

Interestingly, if I swap which line is first, it works. Hopefully that makes its easier to pin down the problem.
![image](https://github.com/a-downing/clothoid/assets/1827346/eba92893-52a7-4520-b051-f79155d3a889)

**Comment by a-downing** [comment]
I have a feeling that it has something to do with angles because the last problem I had where it made loops was due to negative angles.

**Comment by a-downing** [comment]
It's definitely the angles. The angle of the first line is 0.25pi and the second line is 1.75pi. The solution it's coming up with is to curve the line around 1.5pi counter-clockwise. I think the way the math from the paper works is everything is counter-clockwise. This could be solved by reformulating all problems to be counter-clockwise blends, but I'm hoping I can just make this work in both cases naturally.

**Comment by krcwrhvgyxzqelljes** [comment]
So if you calculate the area from the given input points you get the cw or ccw dir.
Then this indicates the solution? Or is there a nicer solution?

**Comment by a-downing** [comment]
I got it! I just pushed the changes.

![image](https://github.com/a-downing/clothoid/assets/1827346/46e29376-0872-4234-ad3f-0978973f6cc8)

**Comment by krcwrhvgyxzqelljes** [comment]
Hi Andrew,

Great work!  

![screen01](https://github.com/a-downing/clothoid/assets/167009475/ca29efbe-3c85-4645-bb98-3c68271401a2)

**Comment by a-downing** [comment]
That's awesome
